name: CI — Build & Tests

on:
  push: { branches: [ "main" ] }
  pull_request: { branches: [ "main" ] }
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          # ❌ pas de "cache: npm" quand il n'y a pas de lockfile

      - name: Install deps
        run: npm install --no-audit --no-fund

      - name: Build
        run: npm run build

      - name: Run unit tests
        env:
          CI: true
        run: npx vitest run --reporter=dot
